[
  {
    id: 3868,
    uid: "1677a460-1b6d-439d-a326-98ea90911472",
    strain: "Banana OG",
    cannabinoid_abbreviation: "CBG",
    cannabinoid: "Tetrahydrocannabivarin",
    terpene: "Acetate",
    medical_use: "bronchodilator",
    health_benefit: "prevents infection",
    category: "seeds \u0026 clones",
    type: "sativa",
    buzzword: "pound",
    brand: "Hiku",
  },
  {
    id: 2962,
    uid: "a29d952e-72d1-412f-832a-1be1bdf46f73",
    strain: "Mojito",
    cannabinoid_abbreviation: "∆9THC",
    cannabinoid: "Cannabidivarin",
    terpene: "(-)-Isopulegol",
    medical_use: "anti-psoriatic",
    health_benefit: "reduces risk of artery blockage",
    category: "concentrates",
    type: "sativa",
    buzzword: "eighth",
    brand: "Shore Natural RX",
  },
];
